name: jotaviz-docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - os
  - pandas
  - numpy
  - wheel
  - jupyter
  - matplotlib
  - setuptools
  - scipy
  - glob
  - atexit
  - shutil
  - twine
  - pillow
  - pylint
  - pip
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
  - pip:
      - -e .
